global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi_app:8001']

  - job_name: 'mysql'
    static_configs:
      - targets: ['prometheus_mysql_exporter:9104']
