version: '3.10'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_trad
    volumes:
      - ./bdd:/var/lib/mysql
    ports:
      - "3307:3306"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

volumes:
  db_data:
  grafana_data:

